// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof





var SquareVerifier = artifacts.require('SquareVerifier');

contract('SquareVerifier', accounts => {

    const account_one = accounts[0];
    const account_two = accounts[1];

    describe('test scenario description', function () {
        beforeEach(async function () { 
            this.contract = await SquareVerifier.new({from: account_one});

            // TODO: some more per test initialization
        })

        it('verification with correct proof', async function () { 
            
        })

        it('verification with incorrect proof', async function () { 
            
        })
    });
})
